apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bv-backend-igrs
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-cloudflare
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - backend.bookvault.maniish.in
    secretName: bookvault-cert
  rules:
  - host: backend.bookvault.maniish.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bv-backend-svc
            port:
              number: 80
