# This pipeline is designed to build a Docker image from the repository
# and push it to GitHub Container Registry (ghcr.io) on a code push event
# or manual trigger. It logs in using GitHub secrets, builds the Docker image,
# pushes it to the registry, and then logs out.

name: Build And Push

on:
  push:
    branches:
      - main # Triggers on push to the main branch
  workflow_dispatch: # Allows manually triggering the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry using secrets
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image and tag it
      - name: Build Docker image
        run: docker-compose build
        env:
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: ${{ vars.DOCKER_IMAGE_TAG }}
          DOCKER_MYSQL_USER: ${{ vars.DOCKER_MYSQL_USER }}
          DOCKER_MYSQL_PORT: ${{ vars.DOCKER_MYSQL_PORT }}
          DOCKER_MYSQL_DATABASE: ${{ vars.DOCKER_MYSQL_DATABASE }}
          DOCKER_DATABASE_ENDPOINT: ${{ secrets.DOCKER_DATABASE_ENDPOINT }}
          DOCKER_MYSQL_PASSWORD: ${{ secrets.DOCKER_MYSQL_PASSWORD }}

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
        env:
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: ${{ vars.DOCKER_IMAGE_TAG }}

      # Log out from Docker
      - name: Log out from Docker
        run: docker logout ghcr.io
